travis:
  secure:
    BINSTAR_TOKEN: MdXqJEqCLvu7i2ZoZxAHgNLXJsrgzMTb9BkjlF9XOOyL9bNA+rMpZ1vhd1h1cs0cJHFL6AwYcrthu8sfAWguOiIYKFfmLeX1rAjt/0QuiSoqgEJnA8LGzogu+/1Ivk2TRQNkSIDu39RyVTLuyFDEXjOh9JSAoUo0svByHVBDrEwQsf/3Fb8d90WpOLPlMUDE9vtEtR/EeKdULN+ob0PBPZ0oTw4xihELxvK9SfpYQ4UtG64zKmnkHeLoXO5JjfoEw0WA5xSr3QVx8TPB7QuNIVZZ7CBjPinNNntdl0UWkaJU28jnaXEq8LooOY/81vSyz8EngbVPnLkp3qHPLmbWT5rOT8/d2foW/2ehaSY4y0B3znZulvAySaAelVO7k4O6Li6x1W1ibrNzVxlig7/pjtVnQp75fB4h1lxTdI+0b7pCCKn8k8FuEJgFLRZ4FUAK46A5KPkuFVYwGRGyGFFL5imISoa0PAEjcUlByZbsaLfRVcz4UXSAYMYgzwMfRAmColjyDRY4qgZw532esUvA4RzvHF5nfGJFXEnghQXu4q97zfRXzyA6BFT5vZeG3QsRMImdJB28haEDJMZylHAOMBFaywBznRi3f6tBd5hb8colt4MHa4cAlIVTI2zZao/+2zSMFX/31nVQww64uvZXxzvJgLF8goMcKizos37thmg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
